apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: multi-az-nodepool-clickhouse
spec:
  disruption:
    consolidateAfter: 60s
    consolidationPolicy: WhenEmptyOrUnderutilized
    budgets:
      - duration: 1h
        nodes: 25%
        reasons: [Empty, Underutilized]
        schedule: "0 2 * * *"
  template:
    metadata:
      labels:
        intent: clickhouse-analytics
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: clickhouse-ec2nodeclass
      taints:
        - key: dedicated
          value: clickhouse
          effect: NoSchedule
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: [arm64]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: [m, r]
        - key: karpenter.sh/capacity-type
          operator: In
          values: [spot] # Consider spot for cost-optimized replicas
