apiVersion: v1
items:
- apiVersion: karpenter.k8s.aws/v1
  kind: EC2NodeClass
  metadata:
    finalizers:
    - karpenter.k8s.aws/termination
    generation: 5
    labels:
      k8slens-edit-resource-version: v1
    name: mongo
  spec:
    amiSelectorTerms:
    - alias: bottlerocket@latest
    blockDeviceMappings:
    - deviceName: /dev/xvdb
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 50Gi
        volumeType: gp3
    kubelet:
      imageGCHighThresholdPercent: 80
      imageGCLowThresholdPercent: 60
    metadataOptions:
      httpEndpoint: enabled
      httpProtocolIPv6: disabled
      httpPutResponseHopLimit: 1
      httpTokens: required
    role: AmazonEKSNodeRole-dev
    securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks_cluster_dev
    subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks_cluster_dev
    tags:
      IntentLabel: apps
      KarpenterNodePoolName: default
      NodeType: default
      intent: apps
      karpenter.sh/discovery: eks_cluster_dev
      project: karpenter-blueprints
kind: List
metadata:
  resourceVersion: ""