apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: mongodb-pool
spec:
  disruption:
    budgets:
    - duration: 1h
      nodes: 20%
      reasons:
      - Empty
      - Underutilized
      - Drifted
      schedule: 0 23 * * *
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        intent: mongodb
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: mongo
      taints:
        - key: "mongodb-nodepool"
          value: "true"
          effect: "NoSchedule"        
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: [ "medium" , "large" ] 